apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: gettodo 

spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: gettodo
  template: 
    metadata:
      app: gettodo 
    containers: 
    - name: gettodo
      image: anjaliacr.azurecr.io/gettodo:v1 
      ports:
      - containerPort: 3000
      env:
      - name: CONNECTION_STRING
        value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:anjaliserver.database.windows.net,1433;Database=anjalidb;Uid=server;Pwd=#Elemental@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    