apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: gettodo 

spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: gettodo
  template: 
    metadata:
      labels:
        app: gettodo 
    spec:
      containers: 
      - name: gettodo
        image: anjaliacr.azurecr.io/gettodo:v1 
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:anjaliserver.database.windows.net,1433;Database=anjalidb;Uid=anjali;Pwd=#Kashmir@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
      