apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gettodo-ingress

spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: get-todo-api.dhoomdhoom.shop
    http: 
      paths:  
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gettodo
            port:
              number: 80

